version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "./api.sh"

workflows:
  version: 2
  build_test_deploy:
    jobs:
    - deploy
